### ISSUE TITLE
How to get element sequences from ancestral node

### ISSUE THREAD

**Issue by aaannaw** [hillerlab/REforge#9]
Dear author,
I noticed the  element_sequences/el137_10000.fa file in the example directory include sequences in the ancestral node. However, I can not know how to get the sequences in the ancestral node, which are necessary? 

I try to delete the labels for ancestral nodes in the tree_simulation.nwk file `(Cgu,(((Tsw,Pty),Hcr),(Hgl,((Gca,Bsu),(Cho,(Fme,(Fda,(Fdm,(Fan,Fmi)))))))))`;. However I got the error:
 ```
Traceback (most recent call last):
  File "/home/REforge-master/REforge_branch_scoring.py", line 172, in <module>
    sys.exit(__score_branches())
  File "/home/REforge-master/REforge_branch_scoring.py", line 165, in __score_branches
    anc0filter=not args.no_ancestral_filter)
  File "/home/REforge-master/REforge_branch_scoring.py", line 69, in traverse_tree
    sequence = str(sequences[parent.name].seq).replace("-", "")
KeyError: 'Cgu-Tsw'
```
Could you give me any suggestions?
Best wishes!
Na Wan

**Comment by aaannaw** [comment]
Hi,
I used PRANK to generate the ancestral sequences. However, I found for some CNE sequences and some branches, the stubb score can not be calculated. Why?  Could you  give me any explanation for the output?
